---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: atomic-alex
# description will be included in the image's metadata
description: This is my personal OS image. 

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/aurora-dx
image-version: stable # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

#  - type: script
#    snippets:
#      - "curl --proto '=https' --tlsv1.2 -sSf -L https://install.determinate.systems/nix | sh -s -- install ostree --no-confirm --no-start-daemon --persistence=/var/lib/nix"
  - type: dnf
    repos:
      copr:
        - scottames/ghostty
        - ryanabx/cosmic-epoch
    install:
      packages:
        - ghostty
        - nushell
        - cosmic-desktop
    # remove:

  - type: default-flatpaks
    configurations:
      - notify: true # Send notification after install/uninstall is finished (true/false)
        scope: system
        # If no repo information is specified, Flathub will be used by default
        install: # system flatpaks we want all users to have and not remove
          # Browsers
          - com.google.Chrome
          - com.brave.Browser
          # File Utils
          - com.dropbox.Client
          - com.github.zocker_160.SyncThingy
          # Media Creation
          - org.audacityteam.Audacity
          - org.gimp.GIMP
          - org.inkscape.Inkscape
          - org.kde.krita
          - com.obsproject.Studio
          # Media Players
          - tv.plex.PlexDesktop
          - com.plexamp.Plexamp
          - org.videolan.VLC
          - org.flameshot.Flameshot # screenshot
          - org.keepassxc.KeePassXC
          - md.obsidian.Obsidian
          - com.getpostman.Postman
          - io.github.pwr_solaar.solaar # Logitech mouse driver
      - scope: user # Also add Flathub user repo, but no user packages

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
  - type: systemd
    system:
      disabled:
        - sddm.service
      enabled:
        - cosmic-greeter.service
        
